services:
    postgres:
        build:
            context: docker/postgres
            dockerfile: Dockerfile
            platforms:
                - "linux/amd64"
            tags:
                - "benchmark/postgres:1.0.0"

        container_name: postgres
        networks:
            - benchmark
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./generate_data/dummy_data:/dummy_data
        restart: on-failure

        healthcheck:
            test: [ "CMD-SHELL", "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1' || exit 1" ]
            interval: 5s
            timeout: 3s
            retries: 3

        deploy:
            mode: global

            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
                max_attempts: 3

            resources:
                limits:
                    cpus: "4"
                    memory: 4096M
                reservations:
                    cpus: "4"
                    memory: 2048M

    pgadmin:
        build:
            context: docker/pgadmin
            dockerfile: Dockerfile
            platforms:
                - "linux/amd64"
            tags:
                - "benchmark/pgadmin:1.0.0"

        container_name: pgadmin
        networks:
            - benchmark
        ports:
            - "${PGADMIN_PORT}:${PGADMIN_PORT}"
        volumes:
            - pgadmin:/var/lib/pgadmin
        environment:
            - PGADMIN_PORT=${PGADMIN_PORT:-80}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=true
            - PGADMIN_CONFIG_LOGIN_BANNER="Authorized users only."
            - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL="DEBUG"
        depends_on:
            postgres:
                condition: service_healthy

        restart: unless-stopped

    mongo:
        image: mongo:6.0
        container_name: mongo
        environment:
         - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
         - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
         - MONGO_USER=${MONGO_USER}
         - MONGO_PASSWORD=${MONGO_PASSWORD}
         - MONGO_DB=${MONGO_DB}
        ports:
            - "${MONGO_PORT}:${MONGO_PORT}"
        volumes:
            - mongo_data:/data/db
            - ./docker/mongo/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
            - ./generate_data/dummy_data:/dummy_data
        networks:
            - benchmark
        healthcheck:
            test: ["CMD-SHELL", "mongosh --username ${MONGO_USER} --password ${MONGO_PASSWORD} --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 })' || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 20s

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        ports:
        - "${ME_PORT}:${ME_PORT}"
        environment:
         - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
         - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
         - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
         - ME_CONFIG_BASICAUTH_USERNAME=${ME_USER}
         - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASSWORD}
         - ME_CONFIG_MONGODB_SERVER=mongo
         - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        depends_on:
            mongo:
                condition: service_healthy
        networks:
            - benchmark

volumes:
    pgadmin:
    postgres:
    mongo_data:

networks:
    benchmark:
        driver: bridge